# Name of your workflow
name: React CI/CD Pipeline

# ---===[ 1. TRIGGERS ]===---
# This section defines WHEN the workflow will run.
on:
  # Run on pushes to the 'main' branch (this is for Deployment)
  push:
    branches: [ "main" ]
    
  # Run on pull requests targeting 'main' or 'develop' (this is for CI)
  pull_request:
    branches: [ "main", "development" ]

# ---===[ 2. PERMISSIONS ]===---
# These permissions are required for the workflow to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# ---===[ 3. JOBS ]===---
# Workflows are made of one or more "jobs"
jobs:
  # ---===[ JOB 1: Continuous Integration (CI) ]===---
  build_and_test:
    name: Build & Test
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use a stable Node.js version
          cache: 'npm' # Cache 'npm' dependencies for faster builds

      # Step 3: Install all project dependencies
      - name: Install Dependencies
        run: npm ci  # 'npm ci' is faster and safer for pipelines than 'npm install'

      # Step 4: Run your tests (if you have them)
      # This assumes you have a "test" script in your package.json
      # (e.g., "test": "react-scripts test" or "test": "vitest")
      - name: Run Tests
        run: npm test

      # Step 5: Build the React application
      # This assumes you have a "build" script in package.json
      - name: Build Project
        run: npm run build

      # Step 6: Save the built code as an "artifact"
      # This artifact will be used by the 'deploy' job later
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          # --- IMPORTANT ---
          # Check your build output folder!
          # create-react-app uses 'build'
          # Vite (which you seem to be using) uses 'dist'
          path: ./dist

  # ---===[ JOB 2: Continuous Deployment (CD) ]===---
  deploy:
    name: Deploy to GitHub Pages
    # This job 'needs' the 'build_and_test' job to succeed first
    needs: build_and_test
    
    # --- IMPORTANT ---
    # This 'if' condition ensures this job ONLY runs on a push
    # to the 'main' branch, and NOT on pull requests.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the 'production-build' artifact from the previous job
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: ./dist # Download it to the 'dist' folder

      # Step 2: Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Step 3: Upload the static site artifact for GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Upload the contents of the 'dist' folder

      # Step 4: Deploy the site!
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4